### ISSUE TITLE
数据集报错

### ISSUE THREAD

**Issue by 1125690278** [autoliuweijie/FastBERT#23]
用你的数据集thucnews跑多分类是OK的，用自己的数据集一直出现这个错误，请问数据集需要怎么处理吗？
Traceback (most recent call last):
  File "run_fastbert.py", line 652, in <module>
    main()
  File "run_fastbert.py", line 589, in main
    result = evaluate(args, False, False)
  File "run_fastbert.py", line 445, in evaluate
    p = confusion[i,i].item()/confusion[i,:].sum().item()
ZeroDivisionError: division by zero

**Comment by hiber-niu** [comment]
我也遇到同样的问题，请问解决了吗？

**Comment by 1125690278** [comment]
> 我也遇到同样的问题，请问解决了吗？

暂时还没解决，解决了请告知一下

**Comment by BshoterJ** [comment]
试试调小些bs呢？可能是上来把所有数据训成某一类了

**Comment by Franklwl** [comment]
line 455-459:
      for i in range(confusion.size()[0]):
          mu = confusion[i, :].sum().item()
          p = confusion[i, i].item() / mu if mu != 0. else 0
          r = confusion[i, i].item() / mu if mu != 0. else 0
          f1 = 2 * p * r / (p + r) if (p + r) != 0. else 0
is OK!
