### ISSUE TITLE
多分类的效果问题

### ISSUE THREAD

**Issue by qsong4** [autoliuweijie/FastBERT#7]
不知道作者有没有在复杂的分类数据集上尝试过该模型，我尝试在一个40分类的数据集上所有样本的不确定性都在0.95以上。

**Comment by autoliuweijie** [comment]
如果标签过多，可以考虑只选概率最高的前top N个概率计算uncertainty。比如N取5。

**Comment by 1125690278** [comment]
请问有多分类的源码吗

**Comment by 1125690278** [comment]
> 如果标签过多，可以考虑只选概率最高的前top N个概率计算uncertainty。比如N取5。
我是初学小白，请问代码里怎么修改N

**Comment by qsong4** [comment]
在inference那里可以对计算出来的prob去TOPN, 只用N个来计算uncertainty

**Comment by 1125690278** [comment]
> 不知道作者有没有在复杂的分类数据集上尝试过该模型，我尝试在一个40分类的数据集上所有样本的不确定性都在0.95以上。

请问您在自己的数据集上做多分类时是否遇到过这种错误：
Traceback (most recent call last):
File "run_fastbert.py", line 652, in
main()
File "run_fastbert.py", line 589, in main
result = evaluate(args, False, False)
File "run_fastbert.py", line 445, in evaluate
p = confusion[i,i].item()/confusion[i,:].sum().item()
ZeroDivisionError: division by zero
是数据集需要经过怎样的处理吗

**Comment by Brain97** [comment]
> 不知道作者有没有在复杂的分类数据集上尝试过该模型，我尝试在一个40分类的数据集上所有样本的不确定性都在0.95以上。

您好，我也想看一下fastbert在多分类场景下的表现，请问您这个40个类的数据集是公开的还是您自己的呀？
